// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Active.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Active_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Active_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Active_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Active_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Active_2eproto;
class ActiveData;
struct ActiveDataDefaultTypeInternal;
extern ActiveDataDefaultTypeInternal _ActiveData_default_instance_;
class ReqActiveConf;
struct ReqActiveConfDefaultTypeInternal;
extern ReqActiveConfDefaultTypeInternal _ReqActiveConf_default_instance_;
class ReqActiveData;
struct ReqActiveDataDefaultTypeInternal;
extern ReqActiveDataDefaultTypeInternal _ReqActiveData_default_instance_;
class ResActiveConf;
struct ResActiveConfDefaultTypeInternal;
extern ResActiveConfDefaultTypeInternal _ResActiveConf_default_instance_;
class ResActiveData;
struct ResActiveDataDefaultTypeInternal;
extern ResActiveDataDefaultTypeInternal _ResActiveData_default_instance_;
class ResNoticeOptActive;
struct ResNoticeOptActiveDefaultTypeInternal;
extern ResNoticeOptActiveDefaultTypeInternal _ResNoticeOptActive_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ActiveData* Arena::CreateMaybeMessage<::ActiveData>(Arena*);
template<> ::ReqActiveConf* Arena::CreateMaybeMessage<::ReqActiveConf>(Arena*);
template<> ::ReqActiveData* Arena::CreateMaybeMessage<::ReqActiveData>(Arena*);
template<> ::ResActiveConf* Arena::CreateMaybeMessage<::ResActiveConf>(Arena*);
template<> ::ResActiveData* Arena::CreateMaybeMessage<::ResActiveData>(Arena*);
template<> ::ResNoticeOptActive* Arena::CreateMaybeMessage<::ResNoticeOptActive>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ReqActiveData final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:ReqActiveData) */ {
 public:
  inline ReqActiveData() : ReqActiveData(nullptr) {}
  explicit PROTOBUF_CONSTEXPR ReqActiveData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReqActiveData(const ReqActiveData& from);
  ReqActiveData(ReqActiveData&& from) noexcept
    : ReqActiveData() {
    *this = ::std::move(from);
  }

  inline ReqActiveData& operator=(const ReqActiveData& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReqActiveData& operator=(ReqActiveData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReqActiveData& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReqActiveData* internal_default_instance() {
    return reinterpret_cast<const ReqActiveData*>(
               &_ReqActiveData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ReqActiveData& a, ReqActiveData& b) {
    a.Swap(&b);
  }
  inline void Swap(ReqActiveData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReqActiveData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReqActiveData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReqActiveData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const ReqActiveData& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const ReqActiveData& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ReqActiveData";
  }
  protected:
  explicit ReqActiveData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ReqActiveData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  friend struct ::TableStruct_Active_2eproto;
};
// -------------------------------------------------------------------

class ActiveData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ActiveData) */ {
 public:
  inline ActiveData() : ActiveData(nullptr) {}
  ~ActiveData() override;
  explicit PROTOBUF_CONSTEXPR ActiveData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ActiveData(const ActiveData& from);
  ActiveData(ActiveData&& from) noexcept
    : ActiveData() {
    *this = ::std::move(from);
  }

  inline ActiveData& operator=(const ActiveData& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActiveData& operator=(ActiveData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ActiveData& default_instance() {
    return *internal_default_instance();
  }
  static inline const ActiveData* internal_default_instance() {
    return reinterpret_cast<const ActiveData*>(
               &_ActiveData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ActiveData& a, ActiveData& b) {
    a.Swap(&b);
  }
  inline void Swap(ActiveData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActiveData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ActiveData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ActiveData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ActiveData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ActiveData& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ActiveData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ActiveData";
  }
  protected:
  explicit ActiveData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParamFieldNumber = 5,
    kIdFieldNumber = 1,
    kTypeFieldNumber = 2,
    kStartTimeFieldNumber = 3,
    kEndTimeFieldNumber = 4,
  };
  // bytes param = 5;
  void clear_param();
  const std::string& param() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_param(ArgT0&& arg0, ArgT... args);
  std::string* mutable_param();
  PROTOBUF_NODISCARD std::string* release_param();
  void set_allocated_param(std::string* param);
  private:
  const std::string& _internal_param() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_param(const std::string& value);
  std::string* _internal_mutable_param();
  public:

  // sint32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // sint32 type = 2;
  void clear_type();
  int32_t type() const;
  void set_type(int32_t value);
  private:
  int32_t _internal_type() const;
  void _internal_set_type(int32_t value);
  public:

  // sint32 startTime = 3;
  void clear_starttime();
  int32_t starttime() const;
  void set_starttime(int32_t value);
  private:
  int32_t _internal_starttime() const;
  void _internal_set_starttime(int32_t value);
  public:

  // sint32 endTime = 4;
  void clear_endtime();
  int32_t endtime() const;
  void set_endtime(int32_t value);
  private:
  int32_t _internal_endtime() const;
  void _internal_set_endtime(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ActiveData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr param_;
  int32_t id_;
  int32_t type_;
  int32_t starttime_;
  int32_t endtime_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Active_2eproto;
};
// -------------------------------------------------------------------

class ResActiveData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ResActiveData) */ {
 public:
  inline ResActiveData() : ResActiveData(nullptr) {}
  ~ResActiveData() override;
  explicit PROTOBUF_CONSTEXPR ResActiveData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ResActiveData(const ResActiveData& from);
  ResActiveData(ResActiveData&& from) noexcept
    : ResActiveData() {
    *this = ::std::move(from);
  }

  inline ResActiveData& operator=(const ResActiveData& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResActiveData& operator=(ResActiveData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResActiveData& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResActiveData* internal_default_instance() {
    return reinterpret_cast<const ResActiveData*>(
               &_ResActiveData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ResActiveData& a, ResActiveData& b) {
    a.Swap(&b);
  }
  inline void Swap(ResActiveData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResActiveData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResActiveData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ResActiveData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ResActiveData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ResActiveData& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResActiveData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ResActiveData";
  }
  protected:
  explicit ResActiveData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
  };
  // repeated .ActiveData data = 1;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  ::ActiveData* mutable_data(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ActiveData >*
      mutable_data();
  private:
  const ::ActiveData& _internal_data(int index) const;
  ::ActiveData* _internal_add_data();
  public:
  const ::ActiveData& data(int index) const;
  ::ActiveData* add_data();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ActiveData >&
      data() const;

  // @@protoc_insertion_point(class_scope:ResActiveData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ActiveData > data_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Active_2eproto;
};
// -------------------------------------------------------------------

class ResNoticeOptActive final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ResNoticeOptActive) */ {
 public:
  inline ResNoticeOptActive() : ResNoticeOptActive(nullptr) {}
  ~ResNoticeOptActive() override;
  explicit PROTOBUF_CONSTEXPR ResNoticeOptActive(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ResNoticeOptActive(const ResNoticeOptActive& from);
  ResNoticeOptActive(ResNoticeOptActive&& from) noexcept
    : ResNoticeOptActive() {
    *this = ::std::move(from);
  }

  inline ResNoticeOptActive& operator=(const ResNoticeOptActive& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResNoticeOptActive& operator=(ResNoticeOptActive&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResNoticeOptActive& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResNoticeOptActive* internal_default_instance() {
    return reinterpret_cast<const ResNoticeOptActive*>(
               &_ResNoticeOptActive_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ResNoticeOptActive& a, ResNoticeOptActive& b) {
    a.Swap(&b);
  }
  inline void Swap(ResNoticeOptActive* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResNoticeOptActive* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResNoticeOptActive* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ResNoticeOptActive>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ResNoticeOptActive& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ResNoticeOptActive& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResNoticeOptActive* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ResNoticeOptActive";
  }
  protected:
  explicit ResNoticeOptActive(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 2,
    kOptFieldNumber = 1,
  };
  // repeated .ActiveData data = 2;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  ::ActiveData* mutable_data(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ActiveData >*
      mutable_data();
  private:
  const ::ActiveData& _internal_data(int index) const;
  ::ActiveData* _internal_add_data();
  public:
  const ::ActiveData& data(int index) const;
  ::ActiveData* add_data();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ActiveData >&
      data() const;

  // sint32 opt = 1;
  void clear_opt();
  int32_t opt() const;
  void set_opt(int32_t value);
  private:
  int32_t _internal_opt() const;
  void _internal_set_opt(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ResNoticeOptActive)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ActiveData > data_;
  int32_t opt_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Active_2eproto;
};
// -------------------------------------------------------------------

class ReqActiveConf final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ReqActiveConf) */ {
 public:
  inline ReqActiveConf() : ReqActiveConf(nullptr) {}
  ~ReqActiveConf() override;
  explicit PROTOBUF_CONSTEXPR ReqActiveConf(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReqActiveConf(const ReqActiveConf& from);
  ReqActiveConf(ReqActiveConf&& from) noexcept
    : ReqActiveConf() {
    *this = ::std::move(from);
  }

  inline ReqActiveConf& operator=(const ReqActiveConf& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReqActiveConf& operator=(ReqActiveConf&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReqActiveConf& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReqActiveConf* internal_default_instance() {
    return reinterpret_cast<const ReqActiveConf*>(
               &_ReqActiveConf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ReqActiveConf& a, ReqActiveConf& b) {
    a.Swap(&b);
  }
  inline void Swap(ReqActiveConf* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReqActiveConf* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReqActiveConf* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReqActiveConf>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReqActiveConf& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ReqActiveConf& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqActiveConf* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ReqActiveConf";
  }
  protected:
  explicit ReqActiveConf(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
  };
  // sint32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ReqActiveConf)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int32_t id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Active_2eproto;
};
// -------------------------------------------------------------------

class ResActiveConf final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ResActiveConf) */ {
 public:
  inline ResActiveConf() : ResActiveConf(nullptr) {}
  ~ResActiveConf() override;
  explicit PROTOBUF_CONSTEXPR ResActiveConf(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ResActiveConf(const ResActiveConf& from);
  ResActiveConf(ResActiveConf&& from) noexcept
    : ResActiveConf() {
    *this = ::std::move(from);
  }

  inline ResActiveConf& operator=(const ResActiveConf& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResActiveConf& operator=(ResActiveConf&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResActiveConf& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResActiveConf* internal_default_instance() {
    return reinterpret_cast<const ResActiveConf*>(
               &_ResActiveConf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(ResActiveConf& a, ResActiveConf& b) {
    a.Swap(&b);
  }
  inline void Swap(ResActiveConf* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResActiveConf* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResActiveConf* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ResActiveConf>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ResActiveConf& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ResActiveConf& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResActiveConf* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ResActiveConf";
  }
  protected:
  explicit ResActiveConf(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // bytes data = 2;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // sint32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ResActiveConf)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  int32_t id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Active_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReqActiveData

// -------------------------------------------------------------------

// ActiveData

// sint32 id = 1;
inline void ActiveData::clear_id() {
  id_ = 0;
}
inline int32_t ActiveData::_internal_id() const {
  return id_;
}
inline int32_t ActiveData::id() const {
  // @@protoc_insertion_point(field_get:ActiveData.id)
  return _internal_id();
}
inline void ActiveData::_internal_set_id(int32_t value) {
  
  id_ = value;
}
inline void ActiveData::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:ActiveData.id)
}

// sint32 type = 2;
inline void ActiveData::clear_type() {
  type_ = 0;
}
inline int32_t ActiveData::_internal_type() const {
  return type_;
}
inline int32_t ActiveData::type() const {
  // @@protoc_insertion_point(field_get:ActiveData.type)
  return _internal_type();
}
inline void ActiveData::_internal_set_type(int32_t value) {
  
  type_ = value;
}
inline void ActiveData::set_type(int32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:ActiveData.type)
}

// sint32 startTime = 3;
inline void ActiveData::clear_starttime() {
  starttime_ = 0;
}
inline int32_t ActiveData::_internal_starttime() const {
  return starttime_;
}
inline int32_t ActiveData::starttime() const {
  // @@protoc_insertion_point(field_get:ActiveData.startTime)
  return _internal_starttime();
}
inline void ActiveData::_internal_set_starttime(int32_t value) {
  
  starttime_ = value;
}
inline void ActiveData::set_starttime(int32_t value) {
  _internal_set_starttime(value);
  // @@protoc_insertion_point(field_set:ActiveData.startTime)
}

// sint32 endTime = 4;
inline void ActiveData::clear_endtime() {
  endtime_ = 0;
}
inline int32_t ActiveData::_internal_endtime() const {
  return endtime_;
}
inline int32_t ActiveData::endtime() const {
  // @@protoc_insertion_point(field_get:ActiveData.endTime)
  return _internal_endtime();
}
inline void ActiveData::_internal_set_endtime(int32_t value) {
  
  endtime_ = value;
}
inline void ActiveData::set_endtime(int32_t value) {
  _internal_set_endtime(value);
  // @@protoc_insertion_point(field_set:ActiveData.endTime)
}

// bytes param = 5;
inline void ActiveData::clear_param() {
  param_.ClearToEmpty();
}
inline const std::string& ActiveData::param() const {
  // @@protoc_insertion_point(field_get:ActiveData.param)
  return _internal_param();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ActiveData::set_param(ArgT0&& arg0, ArgT... args) {
 
 param_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ActiveData.param)
}
inline std::string* ActiveData::mutable_param() {
  std::string* _s = _internal_mutable_param();
  // @@protoc_insertion_point(field_mutable:ActiveData.param)
  return _s;
}
inline const std::string& ActiveData::_internal_param() const {
  return param_.Get();
}
inline void ActiveData::_internal_set_param(const std::string& value) {
  
  param_.Set(value, GetArenaForAllocation());
}
inline std::string* ActiveData::_internal_mutable_param() {
  
  return param_.Mutable(GetArenaForAllocation());
}
inline std::string* ActiveData::release_param() {
  // @@protoc_insertion_point(field_release:ActiveData.param)
  return param_.Release();
}
inline void ActiveData::set_allocated_param(std::string* param) {
  if (param != nullptr) {
    
  } else {
    
  }
  param_.SetAllocated(param, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (param_.IsDefault()) {
    param_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ActiveData.param)
}

// -------------------------------------------------------------------

// ResActiveData

// repeated .ActiveData data = 1;
inline int ResActiveData::_internal_data_size() const {
  return data_.size();
}
inline int ResActiveData::data_size() const {
  return _internal_data_size();
}
inline void ResActiveData::clear_data() {
  data_.Clear();
}
inline ::ActiveData* ResActiveData::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:ResActiveData.data)
  return data_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ActiveData >*
ResActiveData::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:ResActiveData.data)
  return &data_;
}
inline const ::ActiveData& ResActiveData::_internal_data(int index) const {
  return data_.Get(index);
}
inline const ::ActiveData& ResActiveData::data(int index) const {
  // @@protoc_insertion_point(field_get:ResActiveData.data)
  return _internal_data(index);
}
inline ::ActiveData* ResActiveData::_internal_add_data() {
  return data_.Add();
}
inline ::ActiveData* ResActiveData::add_data() {
  ::ActiveData* _add = _internal_add_data();
  // @@protoc_insertion_point(field_add:ResActiveData.data)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ActiveData >&
ResActiveData::data() const {
  // @@protoc_insertion_point(field_list:ResActiveData.data)
  return data_;
}

// -------------------------------------------------------------------

// ResNoticeOptActive

// sint32 opt = 1;
inline void ResNoticeOptActive::clear_opt() {
  opt_ = 0;
}
inline int32_t ResNoticeOptActive::_internal_opt() const {
  return opt_;
}
inline int32_t ResNoticeOptActive::opt() const {
  // @@protoc_insertion_point(field_get:ResNoticeOptActive.opt)
  return _internal_opt();
}
inline void ResNoticeOptActive::_internal_set_opt(int32_t value) {
  
  opt_ = value;
}
inline void ResNoticeOptActive::set_opt(int32_t value) {
  _internal_set_opt(value);
  // @@protoc_insertion_point(field_set:ResNoticeOptActive.opt)
}

// repeated .ActiveData data = 2;
inline int ResNoticeOptActive::_internal_data_size() const {
  return data_.size();
}
inline int ResNoticeOptActive::data_size() const {
  return _internal_data_size();
}
inline void ResNoticeOptActive::clear_data() {
  data_.Clear();
}
inline ::ActiveData* ResNoticeOptActive::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:ResNoticeOptActive.data)
  return data_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ActiveData >*
ResNoticeOptActive::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:ResNoticeOptActive.data)
  return &data_;
}
inline const ::ActiveData& ResNoticeOptActive::_internal_data(int index) const {
  return data_.Get(index);
}
inline const ::ActiveData& ResNoticeOptActive::data(int index) const {
  // @@protoc_insertion_point(field_get:ResNoticeOptActive.data)
  return _internal_data(index);
}
inline ::ActiveData* ResNoticeOptActive::_internal_add_data() {
  return data_.Add();
}
inline ::ActiveData* ResNoticeOptActive::add_data() {
  ::ActiveData* _add = _internal_add_data();
  // @@protoc_insertion_point(field_add:ResNoticeOptActive.data)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ActiveData >&
ResNoticeOptActive::data() const {
  // @@protoc_insertion_point(field_list:ResNoticeOptActive.data)
  return data_;
}

// -------------------------------------------------------------------

// ReqActiveConf

// sint32 id = 1;
inline void ReqActiveConf::clear_id() {
  id_ = 0;
}
inline int32_t ReqActiveConf::_internal_id() const {
  return id_;
}
inline int32_t ReqActiveConf::id() const {
  // @@protoc_insertion_point(field_get:ReqActiveConf.id)
  return _internal_id();
}
inline void ReqActiveConf::_internal_set_id(int32_t value) {
  
  id_ = value;
}
inline void ReqActiveConf::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:ReqActiveConf.id)
}

// -------------------------------------------------------------------

// ResActiveConf

// sint32 id = 1;
inline void ResActiveConf::clear_id() {
  id_ = 0;
}
inline int32_t ResActiveConf::_internal_id() const {
  return id_;
}
inline int32_t ResActiveConf::id() const {
  // @@protoc_insertion_point(field_get:ResActiveConf.id)
  return _internal_id();
}
inline void ResActiveConf::_internal_set_id(int32_t value) {
  
  id_ = value;
}
inline void ResActiveConf::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:ResActiveConf.id)
}

// bytes data = 2;
inline void ResActiveConf::clear_data() {
  data_.ClearToEmpty();
}
inline const std::string& ResActiveConf::data() const {
  // @@protoc_insertion_point(field_get:ResActiveConf.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ResActiveConf::set_data(ArgT0&& arg0, ArgT... args) {
 
 data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ResActiveConf.data)
}
inline std::string* ResActiveConf::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:ResActiveConf.data)
  return _s;
}
inline const std::string& ResActiveConf::_internal_data() const {
  return data_.Get();
}
inline void ResActiveConf::_internal_set_data(const std::string& value) {
  
  data_.Set(value, GetArenaForAllocation());
}
inline std::string* ResActiveConf::_internal_mutable_data() {
  
  return data_.Mutable(GetArenaForAllocation());
}
inline std::string* ResActiveConf::release_data() {
  // @@protoc_insertion_point(field_release:ResActiveConf.data)
  return data_.Release();
}
inline void ResActiveConf::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (data_.IsDefault()) {
    data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ResActiveConf.data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Active_2eproto
