// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Active.proto

#include "Active.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR ReqActiveData::ReqActiveData(
    ::_pbi::ConstantInitialized){}
struct ReqActiveDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReqActiveDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReqActiveDataDefaultTypeInternal() {}
  union {
    ReqActiveData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReqActiveDataDefaultTypeInternal _ReqActiveData_default_instance_;
PROTOBUF_CONSTEXPR ActiveData::ActiveData(
    ::_pbi::ConstantInitialized)
  : id_(0)
  , type_(0)
  , starttime_(0u)
  , endtime_(0u){}
struct ActiveDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ActiveDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ActiveDataDefaultTypeInternal() {}
  union {
    ActiveData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ActiveDataDefaultTypeInternal _ActiveData_default_instance_;
PROTOBUF_CONSTEXPR ResActiveData::ResActiveData(
    ::_pbi::ConstantInitialized)
  : data_(){}
struct ResActiveDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResActiveDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResActiveDataDefaultTypeInternal() {}
  union {
    ResActiveData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResActiveDataDefaultTypeInternal _ResActiveData_default_instance_;
PROTOBUF_CONSTEXPR NotifyOptActive::NotifyOptActive(
    ::_pbi::ConstantInitialized)
  : data_()
  , opt_(0){}
struct NotifyOptActiveDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NotifyOptActiveDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NotifyOptActiveDefaultTypeInternal() {}
  union {
    NotifyOptActive _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NotifyOptActiveDefaultTypeInternal _NotifyOptActive_default_instance_;
static ::_pb::Metadata file_level_metadata_Active_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Active_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Active_2eproto = nullptr;

const uint32_t TableStruct_Active_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ReqActiveData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ActiveData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ActiveData, id_),
  PROTOBUF_FIELD_OFFSET(::ActiveData, type_),
  PROTOBUF_FIELD_OFFSET(::ActiveData, starttime_),
  PROTOBUF_FIELD_OFFSET(::ActiveData, endtime_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ResActiveData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ResActiveData, data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::NotifyOptActive, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::NotifyOptActive, opt_),
  PROTOBUF_FIELD_OFFSET(::NotifyOptActive, data_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ReqActiveData)},
  { 6, -1, -1, sizeof(::ActiveData)},
  { 16, -1, -1, sizeof(::ResActiveData)},
  { 23, -1, -1, sizeof(::NotifyOptActive)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_ReqActiveData_default_instance_._instance,
  &::_ActiveData_default_instance_._instance,
  &::_ResActiveData_default_instance_._instance,
  &::_NotifyOptActive_default_instance_._instance,
};

const char descriptor_table_protodef_Active_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014Active.proto\"\017\n\rReqActiveData\"J\n\nActiv"
  "eData\022\n\n\002id\030\001 \001(\005\022\014\n\004type\030\002 \001(\005\022\021\n\tstart"
  "Time\030\003 \001(\r\022\017\n\007endTime\030\004 \001(\r\"*\n\rResActive"
  "Data\022\031\n\004data\030\001 \003(\0132\013.ActiveData\"9\n\017Notif"
  "yOptActive\022\013\n\003opt\030\001 \001(\005\022\031\n\004data\030\002 \003(\0132\013."
  "ActiveDatab\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_Active_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Active_2eproto = {
    false, false, 218, descriptor_table_protodef_Active_2eproto,
    "Active.proto",
    &descriptor_table_Active_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_Active_2eproto::offsets,
    file_level_metadata_Active_2eproto, file_level_enum_descriptors_Active_2eproto,
    file_level_service_descriptors_Active_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Active_2eproto_getter() {
  return &descriptor_table_Active_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Active_2eproto(&descriptor_table_Active_2eproto);

// ===================================================================

class ReqActiveData::_Internal {
 public:
};

ReqActiveData::ReqActiveData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:ReqActiveData)
}
ReqActiveData::ReqActiveData(const ReqActiveData& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ReqActiveData)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReqActiveData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReqActiveData::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata ReqActiveData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Active_2eproto_getter, &descriptor_table_Active_2eproto_once,
      file_level_metadata_Active_2eproto[0]);
}

// ===================================================================

class ActiveData::_Internal {
 public:
};

ActiveData::ActiveData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:ActiveData)
}
ActiveData::ActiveData(const ActiveData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&endtime_) -
    reinterpret_cast<char*>(&id_)) + sizeof(endtime_));
  // @@protoc_insertion_point(copy_constructor:ActiveData)
}

inline void ActiveData::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&id_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&endtime_) -
    reinterpret_cast<char*>(&id_)) + sizeof(endtime_));
}

ActiveData::~ActiveData() {
  // @@protoc_insertion_point(destructor:ActiveData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ActiveData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ActiveData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ActiveData::Clear() {
// @@protoc_insertion_point(message_clear_start:ActiveData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&endtime_) -
      reinterpret_cast<char*>(&id_)) + sizeof(endtime_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ActiveData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 startTime = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          starttime_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 endTime = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          endtime_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ActiveData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ActiveData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // int32 type = 2;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_type(), target);
  }

  // uint32 startTime = 3;
  if (this->_internal_starttime() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_starttime(), target);
  }

  // uint32 endTime = 4;
  if (this->_internal_endtime() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_endtime(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ActiveData)
  return target;
}

size_t ActiveData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ActiveData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  // int32 type = 2;
  if (this->_internal_type() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_type());
  }

  // uint32 startTime = 3;
  if (this->_internal_starttime() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_starttime());
  }

  // uint32 endTime = 4;
  if (this->_internal_endtime() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_endtime());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ActiveData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ActiveData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ActiveData::GetClassData() const { return &_class_data_; }

void ActiveData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ActiveData *>(to)->MergeFrom(
      static_cast<const ActiveData &>(from));
}


void ActiveData::MergeFrom(const ActiveData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ActiveData)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _internal_set_id(from._internal_id());
  }
  if (from._internal_type() != 0) {
    _internal_set_type(from._internal_type());
  }
  if (from._internal_starttime() != 0) {
    _internal_set_starttime(from._internal_starttime());
  }
  if (from._internal_endtime() != 0) {
    _internal_set_endtime(from._internal_endtime());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ActiveData::CopyFrom(const ActiveData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ActiveData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActiveData::IsInitialized() const {
  return true;
}

void ActiveData::InternalSwap(ActiveData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ActiveData, endtime_)
      + sizeof(ActiveData::endtime_)
      - PROTOBUF_FIELD_OFFSET(ActiveData, id_)>(
          reinterpret_cast<char*>(&id_),
          reinterpret_cast<char*>(&other->id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ActiveData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Active_2eproto_getter, &descriptor_table_Active_2eproto_once,
      file_level_metadata_Active_2eproto[1]);
}

// ===================================================================

class ResActiveData::_Internal {
 public:
};

ResActiveData::ResActiveData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  data_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:ResActiveData)
}
ResActiveData::ResActiveData(const ResActiveData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      data_(from.data_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ResActiveData)
}

inline void ResActiveData::SharedCtor() {
}

ResActiveData::~ResActiveData() {
  // @@protoc_insertion_point(destructor:ResActiveData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ResActiveData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ResActiveData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ResActiveData::Clear() {
// @@protoc_insertion_point(message_clear_start:ResActiveData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ResActiveData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .ActiveData data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_data(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ResActiveData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ResActiveData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .ActiveData data = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_data_size()); i < n; i++) {
    const auto& repfield = this->_internal_data(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ResActiveData)
  return target;
}

size_t ResActiveData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ResActiveData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ActiveData data = 1;
  total_size += 1UL * this->_internal_data_size();
  for (const auto& msg : this->data_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ResActiveData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ResActiveData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ResActiveData::GetClassData() const { return &_class_data_; }

void ResActiveData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ResActiveData *>(to)->MergeFrom(
      static_cast<const ResActiveData &>(from));
}


void ResActiveData::MergeFrom(const ResActiveData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ResActiveData)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  data_.MergeFrom(from.data_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ResActiveData::CopyFrom(const ResActiveData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ResActiveData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResActiveData::IsInitialized() const {
  return true;
}

void ResActiveData::InternalSwap(ResActiveData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  data_.InternalSwap(&other->data_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ResActiveData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Active_2eproto_getter, &descriptor_table_Active_2eproto_once,
      file_level_metadata_Active_2eproto[2]);
}

// ===================================================================

class NotifyOptActive::_Internal {
 public:
};

NotifyOptActive::NotifyOptActive(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  data_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:NotifyOptActive)
}
NotifyOptActive::NotifyOptActive(const NotifyOptActive& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      data_(from.data_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  opt_ = from.opt_;
  // @@protoc_insertion_point(copy_constructor:NotifyOptActive)
}

inline void NotifyOptActive::SharedCtor() {
opt_ = 0;
}

NotifyOptActive::~NotifyOptActive() {
  // @@protoc_insertion_point(destructor:NotifyOptActive)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void NotifyOptActive::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void NotifyOptActive::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void NotifyOptActive::Clear() {
// @@protoc_insertion_point(message_clear_start:NotifyOptActive)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.Clear();
  opt_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NotifyOptActive::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 opt = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          opt_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .ActiveData data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_data(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* NotifyOptActive::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NotifyOptActive)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 opt = 1;
  if (this->_internal_opt() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_opt(), target);
  }

  // repeated .ActiveData data = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_data_size()); i < n; i++) {
    const auto& repfield = this->_internal_data(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NotifyOptActive)
  return target;
}

size_t NotifyOptActive::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NotifyOptActive)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ActiveData data = 2;
  total_size += 1UL * this->_internal_data_size();
  for (const auto& msg : this->data_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int32 opt = 1;
  if (this->_internal_opt() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_opt());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData NotifyOptActive::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    NotifyOptActive::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*NotifyOptActive::GetClassData() const { return &_class_data_; }

void NotifyOptActive::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<NotifyOptActive *>(to)->MergeFrom(
      static_cast<const NotifyOptActive &>(from));
}


void NotifyOptActive::MergeFrom(const NotifyOptActive& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NotifyOptActive)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  data_.MergeFrom(from.data_);
  if (from._internal_opt() != 0) {
    _internal_set_opt(from._internal_opt());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void NotifyOptActive::CopyFrom(const NotifyOptActive& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NotifyOptActive)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NotifyOptActive::IsInitialized() const {
  return true;
}

void NotifyOptActive::InternalSwap(NotifyOptActive* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  data_.InternalSwap(&other->data_);
  swap(opt_, other->opt_);
}

::PROTOBUF_NAMESPACE_ID::Metadata NotifyOptActive::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Active_2eproto_getter, &descriptor_table_Active_2eproto_once,
      file_level_metadata_Active_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ReqActiveData*
Arena::CreateMaybeMessage< ::ReqActiveData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ReqActiveData >(arena);
}
template<> PROTOBUF_NOINLINE ::ActiveData*
Arena::CreateMaybeMessage< ::ActiveData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ActiveData >(arena);
}
template<> PROTOBUF_NOINLINE ::ResActiveData*
Arena::CreateMaybeMessage< ::ResActiveData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ResActiveData >(arena);
}
template<> PROTOBUF_NOINLINE ::NotifyOptActive*
Arena::CreateMaybeMessage< ::NotifyOptActive >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NotifyOptActive >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
