// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FunctionOpen.proto

#include "FunctionOpen.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR ReqFunctionOpenInfo::ReqFunctionOpenInfo(
    ::_pbi::ConstantInitialized){}
struct ReqFunctionOpenInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReqFunctionOpenInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReqFunctionOpenInfoDefaultTypeInternal() {}
  union {
    ReqFunctionOpenInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReqFunctionOpenInfoDefaultTypeInternal _ReqFunctionOpenInfo_default_instance_;
PROTOBUF_CONSTEXPR ResFunctionOpenInfo::ResFunctionOpenInfo(
    ::_pbi::ConstantInitialized)
  : list_()
  , _list_cached_byte_size_(0){}
struct ResFunctionOpenInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResFunctionOpenInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResFunctionOpenInfoDefaultTypeInternal() {}
  union {
    ResFunctionOpenInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResFunctionOpenInfoDefaultTypeInternal _ResFunctionOpenInfo_default_instance_;
PROTOBUF_CONSTEXPR NotifyFunctionOpenUpdate::NotifyFunctionOpenUpdate(
    ::_pbi::ConstantInitialized)
  : list_()
  , _list_cached_byte_size_(0){}
struct NotifyFunctionOpenUpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NotifyFunctionOpenUpdateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NotifyFunctionOpenUpdateDefaultTypeInternal() {}
  union {
    NotifyFunctionOpenUpdate _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NotifyFunctionOpenUpdateDefaultTypeInternal _NotifyFunctionOpenUpdate_default_instance_;
static ::_pb::Metadata file_level_metadata_FunctionOpen_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_FunctionOpen_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_FunctionOpen_2eproto = nullptr;

const uint32_t TableStruct_FunctionOpen_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ReqFunctionOpenInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ResFunctionOpenInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ResFunctionOpenInfo, list_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::NotifyFunctionOpenUpdate, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::NotifyFunctionOpenUpdate, list_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ReqFunctionOpenInfo)},
  { 6, -1, -1, sizeof(::ResFunctionOpenInfo)},
  { 13, -1, -1, sizeof(::NotifyFunctionOpenUpdate)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_ReqFunctionOpenInfo_default_instance_._instance,
  &::_ResFunctionOpenInfo_default_instance_._instance,
  &::_NotifyFunctionOpenUpdate_default_instance_._instance,
};

const char descriptor_table_protodef_FunctionOpen_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022FunctionOpen.proto\"\025\n\023ReqFunctionOpenI"
  "nfo\"#\n\023ResFunctionOpenInfo\022\014\n\004list\030\001 \003(\005"
  "\"(\n\030NotifyFunctionOpenUpdate\022\014\n\004list\030\001 \003"
  "(\005b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_FunctionOpen_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_FunctionOpen_2eproto = {
    false, false, 130, descriptor_table_protodef_FunctionOpen_2eproto,
    "FunctionOpen.proto",
    &descriptor_table_FunctionOpen_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_FunctionOpen_2eproto::offsets,
    file_level_metadata_FunctionOpen_2eproto, file_level_enum_descriptors_FunctionOpen_2eproto,
    file_level_service_descriptors_FunctionOpen_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_FunctionOpen_2eproto_getter() {
  return &descriptor_table_FunctionOpen_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_FunctionOpen_2eproto(&descriptor_table_FunctionOpen_2eproto);

// ===================================================================

class ReqFunctionOpenInfo::_Internal {
 public:
};

ReqFunctionOpenInfo::ReqFunctionOpenInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:ReqFunctionOpenInfo)
}
ReqFunctionOpenInfo::ReqFunctionOpenInfo(const ReqFunctionOpenInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ReqFunctionOpenInfo)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReqFunctionOpenInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReqFunctionOpenInfo::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata ReqFunctionOpenInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_FunctionOpen_2eproto_getter, &descriptor_table_FunctionOpen_2eproto_once,
      file_level_metadata_FunctionOpen_2eproto[0]);
}

// ===================================================================

class ResFunctionOpenInfo::_Internal {
 public:
};

ResFunctionOpenInfo::ResFunctionOpenInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  list_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:ResFunctionOpenInfo)
}
ResFunctionOpenInfo::ResFunctionOpenInfo(const ResFunctionOpenInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      list_(from.list_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ResFunctionOpenInfo)
}

inline void ResFunctionOpenInfo::SharedCtor() {
}

ResFunctionOpenInfo::~ResFunctionOpenInfo() {
  // @@protoc_insertion_point(destructor:ResFunctionOpenInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ResFunctionOpenInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ResFunctionOpenInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ResFunctionOpenInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:ResFunctionOpenInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  list_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ResFunctionOpenInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated int32 list = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_list(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 8) {
          _internal_add_list(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ResFunctionOpenInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ResFunctionOpenInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 list = 1;
  {
    int byte_size = _list_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          1, _internal_list(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ResFunctionOpenInfo)
  return target;
}

size_t ResFunctionOpenInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ResFunctionOpenInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 list = 1;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->list_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _list_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ResFunctionOpenInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ResFunctionOpenInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ResFunctionOpenInfo::GetClassData() const { return &_class_data_; }

void ResFunctionOpenInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ResFunctionOpenInfo *>(to)->MergeFrom(
      static_cast<const ResFunctionOpenInfo &>(from));
}


void ResFunctionOpenInfo::MergeFrom(const ResFunctionOpenInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ResFunctionOpenInfo)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  list_.MergeFrom(from.list_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ResFunctionOpenInfo::CopyFrom(const ResFunctionOpenInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ResFunctionOpenInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResFunctionOpenInfo::IsInitialized() const {
  return true;
}

void ResFunctionOpenInfo::InternalSwap(ResFunctionOpenInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  list_.InternalSwap(&other->list_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ResFunctionOpenInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_FunctionOpen_2eproto_getter, &descriptor_table_FunctionOpen_2eproto_once,
      file_level_metadata_FunctionOpen_2eproto[1]);
}

// ===================================================================

class NotifyFunctionOpenUpdate::_Internal {
 public:
};

NotifyFunctionOpenUpdate::NotifyFunctionOpenUpdate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  list_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:NotifyFunctionOpenUpdate)
}
NotifyFunctionOpenUpdate::NotifyFunctionOpenUpdate(const NotifyFunctionOpenUpdate& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      list_(from.list_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:NotifyFunctionOpenUpdate)
}

inline void NotifyFunctionOpenUpdate::SharedCtor() {
}

NotifyFunctionOpenUpdate::~NotifyFunctionOpenUpdate() {
  // @@protoc_insertion_point(destructor:NotifyFunctionOpenUpdate)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void NotifyFunctionOpenUpdate::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void NotifyFunctionOpenUpdate::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void NotifyFunctionOpenUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:NotifyFunctionOpenUpdate)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  list_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NotifyFunctionOpenUpdate::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated int32 list = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_list(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 8) {
          _internal_add_list(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* NotifyFunctionOpenUpdate::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NotifyFunctionOpenUpdate)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 list = 1;
  {
    int byte_size = _list_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          1, _internal_list(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NotifyFunctionOpenUpdate)
  return target;
}

size_t NotifyFunctionOpenUpdate::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NotifyFunctionOpenUpdate)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 list = 1;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->list_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _list_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData NotifyFunctionOpenUpdate::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    NotifyFunctionOpenUpdate::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*NotifyFunctionOpenUpdate::GetClassData() const { return &_class_data_; }

void NotifyFunctionOpenUpdate::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<NotifyFunctionOpenUpdate *>(to)->MergeFrom(
      static_cast<const NotifyFunctionOpenUpdate &>(from));
}


void NotifyFunctionOpenUpdate::MergeFrom(const NotifyFunctionOpenUpdate& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NotifyFunctionOpenUpdate)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  list_.MergeFrom(from.list_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void NotifyFunctionOpenUpdate::CopyFrom(const NotifyFunctionOpenUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NotifyFunctionOpenUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NotifyFunctionOpenUpdate::IsInitialized() const {
  return true;
}

void NotifyFunctionOpenUpdate::InternalSwap(NotifyFunctionOpenUpdate* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  list_.InternalSwap(&other->list_);
}

::PROTOBUF_NAMESPACE_ID::Metadata NotifyFunctionOpenUpdate::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_FunctionOpen_2eproto_getter, &descriptor_table_FunctionOpen_2eproto_once,
      file_level_metadata_FunctionOpen_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ReqFunctionOpenInfo*
Arena::CreateMaybeMessage< ::ReqFunctionOpenInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ReqFunctionOpenInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::ResFunctionOpenInfo*
Arena::CreateMaybeMessage< ::ResFunctionOpenInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ResFunctionOpenInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::NotifyFunctionOpenUpdate*
Arena::CreateMaybeMessage< ::NotifyFunctionOpenUpdate >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NotifyFunctionOpenUpdate >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
